FROM ewolff/docker-java
COPY target/microservice-consuldns-demo-hystrix-dashboard-0.0.1-SNAPSHOT.jar .
CMD /usr/bin/java -Xmx400m -Xms400m -jar microservice-consuldns-demo-hystrix-dashboard-0.0.1-SNAPSHOT.jar
EXPOSE 8989
